require:
  - rubocop-rails


AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods:
    - 'describe'
    - 'context'

    # Run rubocop --require rubocop-rails
